autoTest/urls.py
# -*- coding:utf-8 -*-
from django.urls import path,re_path
from django.views.decorators.cache import cache_page
from . import views

app_name = 'autoTest'
urlpatterns = [
    path(r'index/', views.index),

    path(r'pro_index/', views.pro_index, name='pro_index'),
    path(r'pro_add/', views.pro_add, name='pro_add'),
    path(r'pro_update/', views.pro_update, name='pro_update'),
    path(r'pro_delete/', views.pro_delete, name='pro_delete'),

    path(r'env_index/', views.env_index, name='env_index'),
    path(r'env_add/', views.env_add, name='env_add'),
    path(r'env_update/', views.env_update, name='env_update'),
    path(r'env_delete/', views.env_delete, name='env_delete'),

    path(r'api_index/', views.api_index, name='api_index'),
    path(r'api_add/', views.api_add, name='api_add'),
    path(r'api_update/', views.api_update, name='api_update'),
    path(r'api_delete/', views.api_delete, name='api_delete'),

    path(r'function_index/', views.function_index, name='function_index'),
    path(r'function_add/', views.function_add, name='function_add'),
    path(r'function_update/', views.function_update, name='function_update'),
    path(r'function_delete/', views.function_delete, name='function_delete'),

    path(r'testStep_index/', views.testStep_index, name='testStep_index'),
    path(r'testStep_add/', views.testStep_add, name='testStep_add'),
    path(r'testStep_update/', views.testStep_update, name='testStep_update'),
    path(r'testStep_delete/', views.testStep_delete, name='testStep_delete'),
    path(r'testStep_run/', views.testStep_run, name='testStep_run'),
    
    path(r'testCases_index/', views.testCases_index, name='testCases_index'),
    path(r'testCases_add/', views.testCases_add, name='testCases_add'),
    path(r'testCases_update/', views.testCases_update, name='testCases_update'),
    path(r'testCases_delete/', views.testCases_delete, name='testCases_delete'),
    path(r'testCases_run/', views.testCases_run, name='testCases_run'),

    path(r'report_index/', views.report_index, name='report_index'),
    path(r'report_show/', views.report_show, name='report_show'),
    path(r'report_delete/', views.report_delete, name='report_delete'),

    path(r'plan_index/', views.plan_index, name='plan_index'),

    path(r'mockServer_index/', views.mockServer_index, name='mockServer_index'),
    path(r'mockServer_add/', views.mockServer_add, name='mockServer_add'),
    path(r'mockServer_update/', views.mockServer_update, name='mockServer_update'),
    path(r'mockServer_delete/', views.mockServer_delete, name='mockServer_delete'),
    
    path(r'find_data/', views.find_data, name='find_data'),

]

testGo/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic.base import RedirectView
from autoTest import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'index/', views.index),
    path(r'', views.index),
    path(r'autoTest/', views.index),
    path(r'autoTest/', include('autoTest.urls')),
    re_path(r'.*/', views.run_mock_server, name='mock_server'),#用于跳转至mock服务
    path("favicon.ico", RedirectView.as_view(url=r'/static/img/yjsLogo.jpg')),
]

autoTest/views.py
from ast import literal_eval
from autoTest import goFunction
import datetime
from django.shortcuts import render, render_to_response, get_object_or_404
from django.http import HttpResponse, JsonResponse, HttpResponseForbidden
from .models import Project, Environment, Api, TestStep, TestCases, Report, MockServer, Function
from django.http import Http404, HttpResponseRedirect
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.cache import cache_page
from django.db import connection
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django_celery_beat.models import IntervalSchedule, CrontabSchedule, PeriodicTask
from django.template import Context
from httprunner import HttpRunner
import json
import locust
import logging
import os
import pprint
import requests
import time

logger = logging.getLogger('testGo.app')
hrun_base_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), r'httprunner/tests/testcases')

'''
登录验证装饰器
def login_check(func):
    def wrapper(request, *args, **kwargs):
        if not request.session.get('login_status'):
            return HttpResponseRedirect('/api/login/')
        return func(request, *args, **kwargs)

    return wrapper
'''

# @cache_page(60 * 10)
def index(request):
    pro_count = Project.objects.count()
    env_count = Environment.objects.count()
    api_count = Api.objects.count()
    testStep_count = TestStep.objects.count()
    testCases_count = TestCases.objects.count()
    report_count = Report.objects.count()
    plan_count = PeriodicTask.objects.count()
    mockServer_count = MockServer.objects.count()
    # 最近五天的日期列表
    summary_col_name_list = []
    today = datetime.datetime.now()
    today_format = today.strftime('%Y-%m-%d')
    summary_col_name_list.append(today_format)
    for day in range(1,5):
        loop_day = today + datetime.timedelta(days=-day)
        loop_day_format = loop_day.strftime('%Y-%m-%d')
        summary_col_name_list.append(loop_day_format)
    #  列表翻转，左边是过去时间，最右边是当天 e.g. ['2019-01-01','2019-01-02','2019-01-03','2019-01-04','2019-01-05',]
    summary_col_name_list.reverse()

    success_list = []
    fail_list = []
    for date in summary_col_name_list:
        filter_report = Report.objects.filter(create_time__startswith=date)
        successes = 0
        failures = 0
        for report in filter_report:
            try:
                #  e.g. run_stat = [3,2,1]
                run_stat = json.loads(report.run_stat)
                successes += int(run_stat[1])
                failures += int(run_stat[2])
            except Exception as e:
                logger.warning(e)
                continue
        success_list.append(successes)
        fail_list.append(failures)


    return render(request, 'autoTest/index.html', context={
        'pro_count': pro_count,
        'env_count': env_count,
        'api_count': api_count,
        'testStep_count': testStep_count,
        'testCases_count': testCases_count,
        'report_count': report_count,
        'plan_count': plan_count,
        'mockServer_count': mockServer_count,
        'summary_col_name_list': summary_col_name_list,
        'success_list': success_list,
        'fail_list': fail_list
    })


def pro_index(request):
    pro_sum = Project.objects.all().order_by('pro_id')
    paginator = Paginator(pro_sum, 10)
    page = request.GET.get('page', 1)
    current_page = int(page)
    try:
        pro_list = paginator.page(page)  # 获取当前页码的记录
    except PageNotAnInteger:
        pro_list = paginator.page(1)  # 如果用户输入的页码不是整数时,显示第1页的内容
    except EmptyPage:
        pro_list = paginator.page(paginator.num_pages)  # 如果用户输入的页数不在系统的页码列表中时,显示最后一页的内容
    if pro_list.has_previous():
        previous_page_index = pro_list.previous_page_number()
    else:
        previous_page_index = None
    if pro_list.has_next():
        next_page_index = pro_list.next_page_number()
    else:
        next_page_index = None
    return render(request, 'autoTest/pro_index.html', context={'pro_list': pro_list,
                                                               'paginator': paginator,
                                                               'current_page': current_page,
                                                               'previous_page_index': previous_page_index,
                                                               'next_page_index': next_page_index
                                                               })


def pro_add(request):
    if request.method == 'POST':
        pro_name = request.POST['pro_name']
        description = request.POST['description']
        pro = Project(pro_name=pro_name, description=description)
        pro.save()
        return HttpResponseRedirect("/autoTest/pro_index/")
    if request.method == 'GET':
        return render(request, 'autoTest/pro_add.html', context={})


def pro_delete(request):
    if request.method == 'GET':
        pro_id = request.GET['pro_id']
        Project.objects.filter(pro_id=pro_id).delete()
        return HttpResponseRedirect("/autoTest/pro_index/")



def pro_update(request):
    if request.method == 'POST':
        pro_id = request.POST['pro_id']
        pro_name = request.POST['pro_name']
        description = request.POST['description']
        Project.objects.filter(pro_id=pro_id).update(pro_name=pro_name, description=description)
        return HttpResponseRedirect("/autoTest/pro_index/")
    if request.method == 'GET':
        pro_id = request.GET['pro_id']
        pro = Project.objects.get(pro_id=pro_id)
        return render(request, 'autoTest/pro_update.html', context={"pro": pro})


def env_index(request):
    page = request.GET.get('page', 1)
    pro_id = request.GET.get('pro_id', '')
    pro_sum = Project.objects.all()
    if pro_id:
        project = Project.objects.get(pro_id=pro_id)
        env_sum = Environment.objects.filter(relative_pro=pro_id)
    else:
        project = None
        env_sum = Environment.objects.all().order_by('env_id')
    paginator = Paginator(env_sum, 10)
    current_page = int(page)
    try:
        env_list = paginator.page(page)  # 获取当前页码的记录
    except PageNotAnInteger:
        env_list = paginator.page(1)  # 如果用户输入的页码不是整数时,显示第1页的内容
    except EmptyPage:
        env_list = paginator.page(paginator.num_pages)  # 如果用户输入的页数不在系统的页码列表中时,显示最后一页的内容
    if env_list.has_previous():
        previous_page_index = env_list.previous_page_number()
    else:
        previous_page_index = None
    if env_list.has_next():
        next_page_index = env_list.next_page_number()
    else:
        next_page_index = None
    return render(request, 'autoTest/env_index.html', context={'env_list': env_list,
                                                               'paginator': paginator,
                                                               'current_page': current_page,
                                                               'previous_page_index': previous_page_index,
                                                               'next_page_index': next_page_index,
                                                               'pro_sum': pro_sum,
                                                               'cur_pro': project,
                                                               })


def env_add(request):
    if request.method == 'POST':
        env_name = request.POST['env_name']
        pro_id = request.POST['pro_id']
        url = request.POST['url']
        port = request.POST['port']
        description = request.POST['description']
        env = Environment(env_name=env_name, url=url, port=port, relative_pro=pro_id,
                          description=description)
        env.save()
        return HttpResponseRedirect("/autoTest/env_index/")
    if request.method == 'GET':
        pro_list = Project.objects.all()
        try:
            cur_env_id = request.GET['env_id']
            cur_env = Environment.objects.get(env_id=cur_env_id)
            cur_pro_id = cur_env.relative_pro
            cur_pro = Project.objects.get(pro_id=cur_pro_id)
        except:
            cur_pro = ''
        return render(request, "autoTest/env_add.html", {"pro_list": pro_list,
                                                         "cur_pro": cur_pro,
                                                         })


def env_delete(request):
    if request.method == 'GET':
        env_id = request.GET['env_id']
        Environment.objects.filter(env_id=env_id).delete()
        return HttpResponseRedirect("/autoTest/env_index/")


def env_update(request):
    if request.method == 'POST':
        env_id = request.POST['env_id']
        env_name = request.POST['env_name']
        pro_id = request.POST['pro_id']
        url = request.POST['url']
        port = request.POST['port']
        description = request.POST['description']
        Environment.objects.filter(env_id=env_id).update(env_name=env_name, url=url, port=port, relative_pro=pro_id,
                                                         description=description)
        return HttpResponseRedirect("/autoTest/env_index/")
    if request.method == 'GET':
        env_id = request.GET['env_id']
        env = Environment.objects.get(env_id=env_id)
        cur_pro = Project.objects.get(pro_id=env.relative_pro)
        pro_list = Project.objects.all()
        return render(request, "autoTest/env_update.html", {"env": env,
                                                            "pro_list": pro_list,
                                                            "cur_pro": cur_pro, })


def api_index(request):
    page = request.GET.get('page', 1)
    pro_id = request.GET.get('pro_id', '')
    pro_sum = Project.objects.all()
    if pro_id:
        project = Project.objects.get(pro_id=pro_id)
        api_sum = Api.objects.filter(relative_pro=pro_id).order_by('api_id')
    else:
        project = None

autoTest/templates/autoTest/api_index.html
{% extends 'autoTest/base.html' %}
{% block title %} 接口管理 {% endblock %}
{% block crumbs %}
    <div class="row">
        <div class="col-md-12">
            <ol class="breadcrumb" style="background-color:initial;">
                <li>
                    <a href="/index/">主页</a>
                </li>
                <li class="active">
                    <a class="this">基础信息</a>
                </li>
                <li class="active">
                    <a class="this-page">接口管理</a>
                </li>
            </ol>

        </div>
    </div>
{% endblock %}

{% block body %}
<div class="row">
    <div class="col-md-12">
        <div class="panel">
            <div class="row panel-heading">
                <div class="col-md-2">
                    <a href="{% url 'autoTest:api_add' %}" class="btn btn-primary">添加接口</a>
                </div>
                <div class="col-md-8"> </div>
                <div class="col-md-2 col-md-offset-8">
                    <div class="dropdown btn-group">
                        <a class="btn btn-primary dropdown-toggle"  id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" >
                        {% if cur_pro %}
                            {{ cur_pro.pro_name }}
                        {% else %}
                            选择所属项目
                        {% endif %}
                        <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                            <li><a href="{% url 'autoTest:api_index' %}">所有环境</a></li>
                            {% for pro in pro_sum %}
                                <li><a href="{% url 'autoTest:api_index' %}?pro_id={{ pro.pro_id }}">{{ pro.pro_name }}</a></li>
                            {% endfor %} 
                        </ul>
                    </div>
                </div>
            </div>
            <div class="panel-body">
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>序号</th>
                        <th>接口名称</th>
                        <th>接口路径</th>
                        <th>请求方式</th>
                        <th>接口内容描述</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for api in api_list %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ api.api_name }}</td>
                        <td>{{ api.api_path }}</td>
                        <td>{{ api.method }}</td>
                        <td>{{ api.description }}</td>
                        <td>
                            <a class="btn btn-sm btn-info" href="{% url 'autoTest:api_update' %}?api_id={{ api.api_id }}" role="button">编辑</a>
                            <button class="btn btn-sm btn-danger" onclick="delcfm(this)" href="{% url 'autoTest:api_delete' %}?api_id={{ api.api_id }}">删除</button>

                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-9 col-lg-offset-5">
        <nav aria-label="Page navigation">
            <ul class="pagination">
                {% if api_list.has_previous %}
                    <li><a href="{% url 'autoTest:api_index'  %}?page={{ previous_page_index }}&pro_id={{ cur_pro.pro_id }}" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
                {% endif %}
                {% for num in paginator.page_range %}
                    {% if num == current_page %}
                        <li class="active"><a href="{% url 'autoTest:api_index'  %}?page={{ num }}&pro_id={{ cur_pro.pro_id }}">{{ num }}</a></li>
                    {% else %}
                        <li class=""><a href="{% url 'autoTest:api_index'  %}?page={{ num }}&pro_id={{ cur_pro.pro_id }}">{{ num }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if api_list.has_next %}
                    <li><a href="{% url 'autoTest:api_index'  %}?page={{ next_page_index }}&pro_id={{ cur_pro.pro_id }}" aria-label="Next"><span aria-hidden="true">&raquo;</span></a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
 </div>
{% endblock %}
{% block javascript %} 
<script type="text/javascript">
    $(document).ready(function () {
        $("#baseinfo > ul > li:eq(2) > a").attr("class","active");
    });
</script>
{% endblock %}

autoTest/templates/autoTest/env_index.html
{% extends 'autoTest/base.html' %}
{% block title %} 环境管理 {% endblock %}
{% block sidebar-nav %} 
<div id="sidebar-nav" class="sidebar">
        <div class="sidebar-scroll">
            <nav>
                <ul class="nav">
                    <li>
                        <a href="/index/"><i class="图标"></i> <span>主页</span></a>
                    </li>
                    <li>
                        <a href="#baseinfo" data-toggle="collapse" class="collapsed">
                            <i class="图标"></i><span>基础信息</span> 
                            <i class="icon-submenu lnr lnr-chevron-left"></i></a>
                        <div id="baseinfo" class="collapse">
                            <ul class="nav">
                                <li><a href="{% url 'autoTest:pro_index' %}" class="">项目管理</a></li>
                                <li><a href="{% url 'autoTest:env_index' %}" class="">环境管理</a></li>
                                <li><a href="{% url 'autoTest:api_index' %}" class="">接口管理</a></li>
                                <li><a href="{% url 'autoTest:testStep_index' %}" class="">用例管理</a></li>
                                <li><a href="{% url 'autoTest:testCases_index' %}" class="">用例集管理</a></li>
                                <li><a href="{% url 'autoTest:report_index' %}" class="">测试报告管理</a></li>
                                <li><a href="{% url 'autoTest:plan_index' %}" class="">执行计划管理</a></li>
                                <li><a href="{% url 'autoTest:mockServer_index' %}" class="">mock服务管理</a></li>
                            </ul>
                        </div>
                    </li>
                    <li>
                        <a href="#system" data-toggle="collapse" class="collapsed">
                            <i class="图标"></i> <span>系统设置</span>
                            <i class="icon-submenu lnr lnr-chevron-left"></i></a>
                        <div id="system" class="collapse">
                            <ul class="nav">
                                <li><a href="{% url 'autoTest:encry_index' %}" class="">签名管理</a></li>
                                <li><a href="#" class="">公共函数管理</a></li>

                            </ul>
                        </div>
                    </li>

                </ul>
            </nav>
        </div>

    </div>
{% endblock %}
{% block crumbs %}
    <div class="row">
        <div class="col-md-12">
            <ol class="breadcrumb" style="background-color:initial;">
                <li>
                    <a href="/index/">主页</a>
                </li>
                <li class="active">
                    <a class="this">基础信息</a>
                </li>
                <li class="active">
                    <a class="this-page">环境管理</a>
                </li>
            </ol>

        </div>
    </div>
{% endblock %}

{% block body %}
<div class="row">
    <div class="col-md-12">
        <div class="panel">
            <div class="row panel-heading">
                <div class="col-md-2">
                    <a href="{% url 'autoTest:env_add' %}" class="btn btn-primary">添加环境</a>
                </div>
                <div class="col-md-8"> </div>
                <div class="col-md-2 col-md-offset-8">
                    <div class="dropdown btn-group">
                        <a class="btn btn-primary dropdown-toggle"  id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" >
                        {% if cur_pro %}
                            {{ cur_pro.pro_name }}
                        {% else %}
                            选择所属项目
                        {% endif %}
                        <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                            <li><a href="{% url 'autoTest:env_index' %}">所有环境</a></li>
                            {% for pro in pro_sum %}
                                <li><a href="{% url 'autoTest:env_index' %}?pro_id={{ pro.pro_id }}">{{ pro.pro_name }}</a></li>
                            {% endfor %} 
                        </ul>
                    </div>
                </div>
            </div>

            <div class="panel-body">
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>序号</th>
                        <th>环境名称</th>
                        <th>域名</th>
                        <th>端口</th>
                        <!-- <th>所属项目</th> -->
                        <th>环境描述</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for env in env_list %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ env.env_name }}</td>
                        <td>{{ env.url }}</td>
                        <td>{{ env.port }}</td>
                        <!-- <td>{{ env.project }}</td> -->
                        <td>{{ env.description }}</td>
                        <td>
                            <a class="btn btn-sm btn-info" href="{% url 'autoTest:env_update' %}?env_id={{ env.env_id }}" role="button">编辑</a>
                            <button class="btn btn-sm btn-danger" onclick="delcfm(this)" href="{% url 'autoTest:env_delete' %}?env_id={{ env.env_id }}">删除</button>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-9 col-lg-offset-5">
        <nav aria-label="Page navigation">
            <ul class="pagination">
                {% if env_list.has_previous %}
                    <li><a href="{% url 'autoTest:env_index'  %}?page={{ previous_page_index }}&pro_id={{ cur_pro.pro_id }}" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
                {% endif %}
                {% for num in paginator.page_range %}
                    {% if num == current_page %}
                        <li class="active"><a href="{% url 'autoTest:env_index'  %}?page={{ num }}&pro_id={{ cur_pro.pro_id }}">{{ num }}</a></li>
                    {% else %}
                        <li class=""><a href="{% url 'autoTest:env_index'  %}?page={{ num }}&pro_id={{ cur_pro.pro_id }}">{{ num }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if env_list.has_next %}
                    <li><a href="{% url 'autoTest:env_index'  %}?page={{ next_page_index }}&pro_id={{ cur_pro.pro_id }}" aria-label="Next"><span aria-hidden="true">&raquo;</span></a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
 </div>
{% endblock %}
{% block javascript %} 
<script type="text/javascript">
    $(document).ready(function () {
        $("#baseinfo > ul > li:eq(1) > a").attr("class","active");
    });
</script>
{% endblock %}

autoTest/templates/autoTest/function_add.html
{% extends 'autoTest/base.html' %}
{% block title %} 添加公共函数 {% endblock %}

{% block crumbs %}
<div class="row">
    <div class="col-md-12">
        <ol class="breadcrumb">
            <li>
                <a href="/index/">主页</a>
            </li>
            <li class="active">
                <a class="this">基础信息</a>
            </li>
            <li class="active">
                <a class="this-page" href="{% url 'autoTest:function_index' %}">公共函数管理</a>
            </li>
            <li class="active">
                <a class="">添加公共函数</a>
            </li>
        </ol>

    </div>
</div>
{% endblock %}

{% block body %}


<div class="row">
    <div class="col-md-12">
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title">添加公共函数</h3>
            </div>
            <div class="panel-body">
                <form class="form-horizontal" method="post" action="{% url 'autoTest:function_add' %}">
                	{% csrf_token %}
                    <div class="form-group">
                        <span style="color: red">*</span>
                        <label for="function_name" class="col-md-2 control-label"><span style="color: red">* </span>公共函数函数:</label>
                        <div class="col-md-6">
                            <input type="text" name="function_name" placeholder="请输入内容" class="form-control" id="function_name">
                        </div>
                    </div>
                    <!-- <div class="form-group">
                        <span style="color: red">*</span>
                        <label for="function_function" class="col-md-2 control-label"><span style="color: red">* </span>公共函数函数:</label>
                        <div class="col-md-6">
                            <input type="text" name="function_function" placeholder="请输入内容" class="form-control" id="function_function">
                        </div>
                    </div> -->
                    <div class="form-group">
                        <label for="function_description" class="col-md-2 control-label">公共函数描述</label>
                        <div class="col-md-6">
                            <textarea name="description" placeholder="请输入内容" class="form-control" id="function_description" rows="3"></textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-4 col-md-6">
                            <button type="submit" class="btn btn-primary">保存</button>
                            <p style="color: red">ps: 添加或者修改公共函数后，请联系管理人员修改公共函数代码！</p>
                        </div>
                    </div>
                </form>
            </div>

        </div>

    </div>

</div>

{% endblock%}

autoTest/templates/autoTest/function_index.html
{% extends 'autoTest/base.html' %}
{% block title %} 公共函数管理 {% endblock %}
{% block crumbs %}
    <div class="row">
        <div class="col-md-12">
            <ol class="breadcrumb" style="background-color:initial;">
                <li>
                    <a href="/index/">主页</a>
                </li>
                <li class="active">
                    <a class="this">基础信息</a>
                </li>
                <li class="active">
                    <a class="this-page">公共函数管理</a>
                </li>
            </ol>

        </div>
    </div>
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-12">
            <div class="panel">
                <div class="panel-heading">
                   <a href="{% url 'autoTest:function_add' %}" class="btn btn-primary">添加公共函数</a>
                </div>
                <div class="panel-body">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>序号</th>
                            <!-- <th>公共函数名称</th> -->
                            <th>公共函数函数</th>
                            <th>公共函数描述</th>
                            <th>操作</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for function in function_list %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ function.function_name }}</td>
                                <td>{{ function.description }}</td>
                                <td>
                                    <a class="btn btn-sm btn-info" href="{% url 'autoTest:function_update' %}?function_id={{ function.function_id }}" role="button">编辑</a>
                                    <button class="btn btn-sm btn-danger" onclick="delcfm(this)" href="{% url 'autoTest:function_delete' %}?function_id={{ function.function_id }}">删除</button>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </div>

    <div class="row">
        <div class="col-md-9 col-lg-offset-5">
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    {% if function_list.has_previous %}
                        <li><a href="{% url 'autoTest:function_index'  %}?page={{ previous_page_index }}" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
                    {% endif %}
                    {% for num in paginator.page_range %}
                        {% if num == current_page %}
                            <li class="active"><a href="{% url 'autoTest:function_index'  %}?page={{ num }}">{{ num }}</a></li>
                        {% else %}
                            <li class=""><a href="{% url 'autoTest:function_index'  %}?page={{ num }}">{{ num }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if function_list.has_next %}
                        <li><a href="{% url 'autoTest:function_index'  %}?page={{ next_page_index }}" aria-label="Next"><span aria-hidden="true">&raquo;</span></a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
{% endblock %}
{% block javascript %} 
<script type="text/javascript">
    $(document).ready(function () {
        $("#system > ul > li:eq(0) > a").attr("class","active");
    });
</script>
{% endblock %}